<a href="https://colab.research.google.com/github/wheemin-2/25-1-ESAA/blob/main/0505_HW_ML_DL_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **인공지능, 머신 러닝과 딥러닝**

인공지능(Artificial Intelligence , AI) : 인간의 지능을 모방하여 사람이 하는 일을 컴퓨터(기계)가 할 수 있도록 하는 기술

인공지능을 구현하는 방법으로 머신 러닝(machine lea rning) 과 답러닝 (dcep learning) 이 있음

![ai/dl/ml](https://thebook.io/img/080289/018.jpg)

**머신러닝과 딥러닝의 차이**

- 머신러닝과 딥러닝 모두 학습 모델을 제공하여 데이터를 분류할 수 있는 기술이지만, 접근 방식에 차이가 있음

[머신 러닝]
- 주어진 데이터를 인간이 먼저 처리(전처리)함
- 이미지 데이터인 경우, 사람이 학습 데이터를 컴퓨터가 인식할 수 있도록 준비해야함

[딥러닝]
- 인간이 하던 작업 생략
- 대량의 데이터를 신경망에 적용하면 컴퓨터가 스스로 분석한 후 답을 찾음

 ![ML/DL](https://thebook.io/img/080289/019.jpg)

[동작원리]

- 머신러닝 : 입력 데이터에 알고리즘을 적용해 예측 수행
- 딥러닝 : 정보를 전달하는 신경망을 사용해 데이터 특징 및 관계 해석

[재사용]

- 머신러닝 : 입력 데이터 분석을 위해 다양한 알고리즘 사용 / 동일 유형의 데이터 분석을 위한 재사용은 불가
- 딥러닝 : 구현된 알고리즙은 동일 유형의 데이터 분석 재사용이 가능

[데이터]

- 머신러닝 : 일반적으로 수천개 데이터 필요
- 딥러닝 : 수백만개 이상의 데이터 필요

[훈련 시간]

- 머신러닝 : 단시간
- 딥러닝 : 장시간

[결과]

- 머신러닝 : 점수 or 분류 등 숫자값
- 딥러닝 : 점수/텍스트/소리 등 어떤 것이든 가능

# **머신 러닝**

## **머신 러닝 학습 과정**

머신 러닝은 크게 학습 단계와 예측 단계로 구분할 수 있음

훈련 데이터를 머신 러닝 알고리즘에 적용하여 "학습" > 이 학습 결과로 모형 생성 > 생성된 모형에 새로운 데이터를 적용하여 결과 "예측"

[머신 러닝의 주요 구성 요소]

- 데이터 : 머신 러닝이 학습 모델을 만드는 데 사용하는 것
    - 훈련 데이터가 나쁘면 실제 현상의 특성을 제대로 반영할 수 X
    - 실제 데이터의 특징이 잘 반영되고 편향되지 않는 훈련 데이터를 확보하는 것이 중요
- 모델 : 머신 러닝 학습 단계에서 얻은 최종 결과물, 가설이라고도 함
    - 모델 선택 > 모델 학습 및 평가 > 평가를 바탕으로 모델 업데이트 : 이 과정을 반복하면서 최적의 모델을 찾음

*훈련과 검증, 테스트 데이터셋*

- 검증 데이터셋을 사용하는 이유? : 모델 성능을 평가 하기 위해서! 즉， 훈련 데이터셋으로 모델을 학습시킨 후 모델이 잘 예측하는지 그 성능을 평가하기 위해서 사용함
    - 하지만 검증 용도의 데이터셋은 훈련 데이터셋의 일부를 떼어서 사용하기 때문에 학습에 사용되는 데이터 셋의 양이 많지 않다면 검증 데이터셋을 사용하는 것은 좋지 않음
- 모델 성능 평가는 왜 필요할까? : 테스트 데이터셋에 대한 성능을 가늠해 볼 수 있고, 모델 성능을 높이는 데에 도움을 줌
    - 훈련 데이터셋에 대한 정확도는 높은데, 검증 데이터셋에 대한 정확도가 낮다 > 과적합 가능성!! > 정규화(Regularization)/epoch 감소 등의 대처 가능

## **머신 러닝 학습 알고리즘**

머신 러닝의 학습 알고리즘으로는 지도 학습, 비지도 학습, 강화 학습이 있음

[지도 학습]
- 정답이 무엇인지 알려주고 학습시키는 방법

[비지도 학습]
- 정답을 알려주지 않고 특징이 비슷한 테이터를 클러스터링하여 예측하는 학습 방법

[강화 학습]
- 분류할 수 있는 데이터 X, 정답 X
- 자신의 행동에 대한 보상을 받으며 학습을 진행
- 보상이 커지는 행동은 자주 하도록 하고, 줄어드는 행동은 덜 하도록 하여 학습을 진행함

![ml algo](https://velog.velcdn.com/images/kwons/post/58fd10c5-d113-4ceb-b9ae-b27c068543a4/image.png)

# **딥러닝**

딥러닝은 인간의 신경망 원리를 모방한 심층 신경망 이론을 기반으로 고안된 머신 러닝 방법의 일종
> 컴퓨터에 뉴런과 시냅스 개념을 적용함, 각각의 뉴런은 복잡하게 연결된 수많은 뉴런을 병렬 연산하여 기존에 컴퓨터가 수행하지 못했던 음성/영상 인식 등의 처리를 가능하게 함

![NN](https://velog.velcdn.com/images/kwons/post/fe2f6d47-88e3-43b0-9ef0-af074f4f04c4/image.png)

## **딥러닝 학습 과정**

![DL algo](https://velog.velcdn.com/images/kwons/post/0218b637-2a55-45ee-bf60-6b04ecc30bbe/image.png)


[모델 정의]
- 신경망을 생성하는 단계
- 일반적으로 은닉층 개수가 많을수록 성능이 좋아지지만 과적합이 발생할 확률이 높아짐 (은닉층 개수에 따른 성능과 과적합은 서로 상충관계)

[모델 컴파일]
- 활성화 함수, 손실 함수, 옵티마이저 선택
    - 활성화 함수 : 입력 신호가 일정 기준 이상이면 출력 신호로 변환하는 함수 (Sigmoid, ReLu 등)
    - 옵티마이저 : 손실 함수를 기반으로 네트워크 업데이트 방법을 결정 (Adam, RMSProp 등)
- 과적합을 피할 수 있는 활성화 함수/옵티마이저 선택이 중요함

[모델 훈련]
- 한 번에 처리할 데이터양을 지정
    - 데이터양 ↑ : 학습 속도 ↓, 메모리 부족 문제 발생 가능
    - 적절하게 설정해야 함
- batch, epoch 선택이 중요
    - batch : 전체 훈련 데이터셋에서 일정 한 묶음으로 나누어 처리할 수 있는 것
    - epoch : 훈련 횟수
    ![batch/epoch](https://thebook.io/img/080289/027.jpg)

[모델 예측]
- 검증 데이터셋을 모델에 적용하여 실제로 예측을 진행하는 단계
- 이때 성능이 낮다면 파라미터 튜닝/신경망 재설계 진행

**batch_size와 epoch**

💡 Epoch란?

> 인공 신경망에서 전체 데이터에 대해서 순전파와 역전파가 끝난 상태

> ex) 전체 데이터를 하나의 문제지에 비유한다면 문제지의 모든 문제를 끝까지 다 풀고, 정답지로 채점을 하여 문제지에 대한 공부를 한 번 끝낸 상태

💡 Batch_size란?

> 몇 개의 데이터 단위로 매개변수를 업데이트 하는지를 말함.

> ex) 문제지에서 몇 개씩 문제를 풀고나서 정답지를 확인하느냐의 문제. 기계 입장에서는 실제값과 예측값으로부터 오차를 계산하고 옵티마이저가 매개변수를 업데이트함.

여기서 중요한 포인트는 **업데이트가 시작되는 시점 = 정답지/실제값을 확인하는 시점**

💡 훈련 데이터셋 1000개에 대한 에포크가 10이고, 배치 크기가 20인 경우

- batch_size=20 : 샘플 단위 20개마다 모델 가중치를 한 번씩 업데이트 >> 총 50번 가중치가 업데이트 됨
- epoch=10 : 가중치 50번 업데이트하는 것을 총 10번 반복
- 결과적으로 가중치는 총 500번 업데이트 됨

**신경망과 역전파**

딥러닝 학습 과정에서 중요한 핵심 구성 요소 : 신경망과 역전파

- 딥러닝은 머신 러닝의 한 분야이지만, 심층 신경망(deep neural network)을 사용한다는 점에서 머신 러닝과 차이가 있음
 - 심층 신경망 : 은닉층이 두 개 이상인 신경망, 데이터셋의 어떤 특성들이 중요한지 스스로에게 가르쳐 줄 수 있는 기능이 있음
 ![deep nn](https://velog.velcdn.com/images/kwons/post/1da6ca2e-0377-4134-be8f-3795e084575d/image.png)

- 역전파 : 가중치 값을 업데이트하는 역할
    - 역전파 계산 과정에서 사용되는 미분(오차를 각 가중치로 미분)이 성능에 영향을 미치는 주요한 요소!
    - 파이토치와 같은 프레임워크는 역전파 알고리즘을 자동으로 처리해주므로 딥러닝 알고리즘 구현이 간단하고 편리해짐
    ![BackPropagation](https://velog.velcdn.com/images/kwons/post/90d6ef29-9058-4afd-9627-213bbd2c385b/image.png)

## **딥러닝 학습 알고리즘**

활용 분야에 따라 지도학습, 비지도 학습, 전이 학습으로 분류됨

![DL algo2](https://velog.velcdn.com/images/kwons/post/79e42c9b-b79f-45af-be3d-c92bc198bd38/image.png)

[지도 학습]
- 이미지 분류
    - 이미지 or 비디오상의 객체를 식별하는 컴퓨터 비전 기술
    - 목적에 따라 이미지분류/이미지인식/이미지분할로 나뉨

    ex) CNN : 합성곱 신경망

- 시계열 데이터 분석
    - RNN (순환신경망) : 시간에 따른 데이터에 사용, but 역전파 과정에서 **기울기 소멸 문제** 발생
    - LSTM : RNN의 문제점을 개선하고자 게이트(gate) 3개 추가
        - 망각게이트/입력게이트/출력게이트를 도입하여 기울기 소멸 문제 해결
        - 현재 시계열 문제에서 가장 활발히 사용 중

[비지도 학습]
- 워드 임베딩
    - 단어를 벡터로 변환하여 컴퓨터가 이해할 수 있도록 함
    - NLP 분야의 일종으로, 번역/음성 인식 등의 서비스에서 사용함
    - Word2Vec, GloVe를 가장 많이 사용
- 군집
    - 아무런 정보가 없는 상태에서 데이터를 분류하는 방법
    - 군집 간은 구분이 되도록, 군집 내 요소들은 비슷하게 구성하는 것이 목표
    - 머신 러닝의 군집과 크게 다르지 않으나, 머신 러닝에서 군집화를 처리할 때 딥러닝과 함께 사용하면 모델 성능을 높일 수 있음

[전이 학습]
- 사전 학습 모델을 이용하여 미세조정기법을 통해 학습시키는 방법
    - 사전 학습 모델 : 풀고자 하는 문제와 비슷하면서 많은 데이터로 이미 학습되어있는 모델

    ex) VGG, 인셉션, MobileNet

# **파이토치**

## **파이토치 특징 및 장점**

> **"GPU에서 텐서 조작 및 동적 신경망 구축이 가능한 프레임워크"**

**GPU (Graphics Processing Unit)** : 연산 속도를 빠르게 하는 역할
- 딥러닝에서는 기울기를 계산할 때 미분을 사용, GPU 사용 시 빠른 계산이 가능
- 병렬 연산에서의 속도 : GPU >> CPU
- 딥러닝 학습에서 GPU 사용은 필수적

**텐서(Tensor)**
- pytorch의 데이터 형태
- 단일 데이터 형식으로 된 자료들의 다차원 행렬
- 간단한 명령어를 사용해 GPU로 연산을 수행하게 할 수 있음

**동적 신경망** : 훈련을 반복할 때마다 네트워크 변경이 가능한 신경망 (ex. 학습 중에 은닉층 추가/제거 등 조작이 가능)

- 'Define by Run' 방식 사용 : 연산 그래프를 정의하는 것과 동시에 값도 초기화 됨
- 연산 그래프와 연산을 분리해서 생각할 필요가 없으므로 코드 이해가 쉬움
 ![define by run](https://velog.velcdn.com/images/kwons/post/8eaecb7f-1aef-4929-a8e2-dfe1ac2dea65/image.png)

**벡터, 행렬, 텐서**

![vector, matrix, tensor](https://thebook.io/img/080289/035_2.jpg)

- 벡터 : 1차원 배열 형태
- 행렬 : 2차원 배열 형태
- 텐서 : 3차원 이상의 배열 형태
- axis 0 : 1차원 축(행), 벡터 / axis 1 : 2차원 축(열), 행렬 / axis 2 : 3차원 축(채널), 텐서

## **파이토치의 아키텍처**

파이토치 아키텍처는 세 개의 계층으로 나누어볼 수 있음

![pytorch arch](https://velog.velcdn.com/images/kwons/post/12e60fd2-de28-4d15-9ce5-c5dcf8fbb95e/image.png)

## **파이토치 API**

파이토치 API 계층에서는 사용자가 이해하기 쉬운 API를 제공하여 텐서에 대한 처리와 신경망을 구축하고 훈련할 수 있도록 도움. 이 계층에서는 사용자 인터페이스를 제공하지만 실제 계산은 수행하지 않고, C++로 작성된 파이토치 엔진으로 그 작업을 전달하는 역할만 함

[파이토치 API 계층에서 제공하는 패키지]
- `torch` : GPU 지원 텐서 패키지
    - 다차원 텐서를 기반으로 다양한 수학적 연산이 가능하도록 함
- `torch.autograd` : 자동 미분 패키지
    - 연산 그래프가 즉시 계산(실시간으로 네트워크 수정이 반영된 계산)되기 때문에 사용자는 다양한 신경망을 적용해볼 수 있음
    
   *일반적으로 신경망에 사소한 변경이 있다면 신경망 구축을 처음부터 다시 시작해야함

- `torch.nn` : 신경망 구축 및 훈련 패키지
- `torch.multiprocessing` : 파이썬 멀티프로세싱 패키지
- `torch.utils` : DataLoader 및 기타 유틸리티 제공

# **파이토치 기초 문법**

## **텐서 다루기**

### **텐서 생성 및 변환**

In [ ]:
import torch
print(torch.tensor([[1,2], [3,4]])) # 2차원 형태의 텐서
#print(torch.tensor([[1,2], [3,4]], device='cuda:0')) # GPU에 텐서 생성
print(torch.tensor([[1,2], [3,4]], dtype=torch.float64))

tensor([[1, 2],
        [3, 4]])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [ ]:
# 텐서를 ndarray로 변환
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy())

#print(torch.tensor([[1,2], [3,4]], device='cuda:0'))
#print(temp.to('cpu').numpy()) # GPU상의 텐서를 CPU의 텐서로 변환 후 ndarrary로 변환

[[1 2]
 [3 4]]


### **텐서의 인덱스 조작**

텐서는 넘파이의 ndarray를 조작하는 것과 유사하게 동작함
> 배열처럼 인덱스를 바로 지정하거나, 슬라이스 등을 사용할 수 있음

[텐서의 자료형]
- `torch.FloatTensor` : 32비트의 부동 소수점
- `torch.DoubleTensor` : 64비트의 부동 소수점
- `torch.LongTensor` : 64비트의 부호가 있는 정수
- 그 외

In [ ]:
temp = torch.FloatTensor([1,2,3,4,5,6,7]) # 1차원 벡터 생성
print(temp[0], temp[1], temp[-1]) # 인덱스로 접근
print('---------------')
print(temp[2:5], temp[4:-1]) # 슬라이스로 접근

tensor(1.) tensor(2.) tensor(7.)
---------------
tensor([3., 4., 5.]) tensor([5., 6.])


### **텐서 연산 및 차원 조작**

[텐서의 연산]

텐서는 넘파이의 ndarray처럼 다양한 수학 연산이 가능, GPU를 사용하면 더 빠르게 연산할 수 있음

**텐서 간의 타입이 다르면 연산이 불가능 !! (ex. FloatTensor와 DoubleTensor 간의 연산 불가능)*

In [ ]:
v = torch.tensor([1,2,3])
w = torch.tensor([3,4,6])
print(w - v)  # elementwise 계산

tensor([2, 2, 3])


[텐서의 차원 조작]
- `view` : 텐서의 차원을 변경하는 가장 대표적인 방법 (np.reshape과 유사)
- `stack`, `cat` : 텐서를 결합
- `t`, `transpose` : 텐서의 차원을 교환

In [ ]:
temp = torch.tensor([[1,2], [3,4]])  # 2x2 mtx

print(temp.shape)
print('-------------------')
print(temp.view(4,1))  # 4x1로 차원 변경
print('-------------------')
print(temp.view(-1)) # 1차원 벡터로 변경
print('-------------------')
print(temp.view(1,-1))
print('-------------------')
print(temp.view(-1,1)) # 2차원 (4,1) 행렬

torch.Size([2, 2])
-------------------
tensor([[1],
        [2],
        [3],
        [4]])
-------------------
tensor([1, 2, 3, 4])
-------------------
tensor([[1, 2, 3, 4]])
-------------------
tensor([[1],
        [2],
        [3],
        [4]])


## **데이터 준비**

[파일을 불러와서 사용]



```
import pandas as pd ------ pandas 라이브러리 호출
import torch ------ torch 라이브러리 호출
data = pd.read_csv('../class2.csv') ------ csv 파일을 불러옵니다.

x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float() ------ CSV 파일의 x 칼럼의 값을 넘파이 배열로 받아 Tensor(dtype)으로 바꾸어 줍니다.
y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float() ------ CSV 파일의 y 칼럼의 값을 넘파이 배열로 받아 Tensor(dtype)으로 바꾸어 줍니다.
```



[커스텀 데이터셋을 만들어서 사용]

커스텀 데이터셋(custom dataset)
- 데이터를 한 번에 다 부르지 않고 조금씩 나누어 불러서 사용하는 방식
- 딥러닝은 기본적으로 대량의 데이터를 이용하여 모델을 학습시키는데, 데이터를 한 번에 불러와서 훈련시키면 시간과 비용 측면에서 효율적이지 않음



```
# 기본 구조
class CustomDataset(torch.utils.data.Dataset):
    def __init __(self): ------ 필요한 변수를 선언하고, 데이터셋의 전처리를 해 주는 함수
    def __len __(self): ------ 데이터셋의 길이. 즉, 총 샘플의 수를 가져오는 함수
    def __getitem __(self, index): ------ 데이터셋에서 특정 데이터를 가져오는 함수
                                (index번째 데이터를 반환하는 함수이며, 이때 반환되는 값은 텐서의 형태를 취해야 합니다)
```



In [ ]:
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):
    def __init__(self, csv_file):   # 데이터 불러오기
        self.label = pd.read_csv(csv_file)

    def __len__(self):     # 데이터셋의 크기 반환
        return len(self.label)

    def __getitem__(self, idx):    # 특정 데이터를 반환(idx 번째의 데이터 반환)
        sample = torch.tensor(self.label.iloc[idx,0:3]).int()
        label = torch.tensor(self.label.iloc[idx,3]).int()
        return sample, label

#tensor_dataset = CustomDataset('../covtype.csv')
#dataset = DataLoader(tensor_dataset, batch_size=4, shuffle=True)   # 원하는 만큼만 가져

**torch.utils.data.DataLoader**

- 데이터로더(DataLoader) 객체는 학습에 사용될 데이터 전체를 보관했다가 모델 학습을 할 때 배치 크기만큼 데이터를 꺼내서 사용
- 데이터를 미리 잘라 놓는 것이 아니라 내부적으로 반복자(iterator)에 포함된 인덱스(index)를 이용하여 배치 크기만큼 데이터를 반환함!!

![dataloader](https://thebook.io/img/080289/048.jpg)



```
# 다음과 같이 작동함
for i, data in enumerate(dataset,0):
    print(i, end='')
    batch=data[0]
    print(batch.size())

# 출력 결과
0torch.Size([4, 3])
1torch.Size([4, 3])
2torch.Size([4, 3])
3torch.Size([4, 3])
4torch.Size([3, 3])
```





[파이토치에서 제공하는 데이터셋 사용]

토치비전(torchvision) : 파이토치에서 제공하는 데이터셋이 모여 있는 패키지
- MNIST, ImageNet을 포함한 유명 데이터셋을 제공

In [ ]:
# 파이토치에서 제공하는 데이터셋을 내려받으려면 requests 라이브러리 설치 필요
!pip install requests

In [ ]:
# MNIST 데이터 내려받기
import torchvision.transforms as transforms

mnist_transform = transforms.Compose([transforms.ToTensor(),
                                      transforms.Normalize((0.5,), (1.0))]) # 평균이 0.5, sd가 1이 되도록 데이터 분포 조정

from torchvision.datasets import MNIST
import requests

download_root = '../chap02/data/MNIST_DATASET' # 내려받을 경로 지정
train_dataset = MNIST(download_root, transform=mnist_transform, train=True, download=True)
valid_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)
test_dataset = MNIST(download_root, transform=mnist_transform, train=False, download=True)

100%|██████████| 9.91M/9.91M [00:00<00:00, 18.1MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 489kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.54MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 8.06MB/s]


## **모델 정의**

파이토치에서 모델을 정의하기 위해서는 모듈을 상속한 클래스를 사용

- 계층(layer) : 모듈 또는 모듈을 구성하는 한 개의 계층으로, 합성곱층(convolutional layer), 선형 계층(linear layer) 등이 있음
- 모듈(module) : 한 개 이상의 계층이 모여서 구성된 것, 모듈이 모여 새로운 모듈을 만드는 것도 가능
- 모델(model) : 최종적으로 원하는 네트워크, 한 개의 모듈이 모델이 될 수도 있음

### **단순 신경망 정의**

nn.Module을 상속받지 않는 매우 단순한 모델을 만들 때 사용, 구현이 쉽고 단순함

```
model = nn.Linear(in_features=1, out_features=1, bias=True)
```

### **nn.Module()을 상속하여 정의**

파이토치에서 nn.Module을 상속받는 모델은 기본적으로 __init__()과 forward() 함수를 포함
- __init__() : 모델에서 사용될 모듈(nn.Linear, nn.Conv2d), 활성화 함수 등을 정의
- forward() : 모델에서 실행되어야 하는 연산을 정의

In [ ]:
from torch.nn import Module, Linear, Sigmoid

class MLP(Module):
    def __init__(self, inputs):
        super(MLP, self).__init__()
        self.layer = Linear(inputs, 1)  # 계층 정의
        self.activation = Sigmoid()   # 활성화 함수 정의
    def forward(self, X):
        X = self.layer(X)
        X = self.activation(X)
        return X

### **Sequential 신경망 정의**

`nn.Sequential`을 사용하면 __init__()에서 사용할 네트워크 모델들을 정의해 줄 뿐만 아니라 forward() 함수에서는 모델에서 실행되어야 할 계산을 좀 더 가독성이 뛰어나게 코드로 작성할 수 있음.

- Sequential 객체는 그 안에 포함된 각 모듈을 순차적으로 실행함
- 모델의 계층이 복잡할 수록 효과가 뛰어남

In [ ]:
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=64, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2)
        )
        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels=30, kernel_size=5),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2)
        )
        self.layer3 = nn.Sequential(
            nn.Linear(in_features=30*5*5, out_features=10, bias=True),
            nn.ReLU(inplace=True)
        )

        def forward(self, x):
            x = self.layer1(x)
            x = self.layer2(x)
            x = x.view(x.shape[0],-1)
            x = self.layer3(x)
            return x

model = MLP()  # 모델에 대한 객체 생성

print('Printing childern\n---------------------')
print(list(model.children()))
print('\n\nPrinting Modules\n---------------------')
print(list(model.modules()))

Printing childern
---------------------
[Sequential(
  (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
)]


Printing Modules
---------------------
[MLP(
  (layer1): Sequential(
    (0): Conv2d(3, 64, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (layer3): Sequential(
    (0): Linear(in_features=750,

**model.modules() & model.children()**

`model.modules()` : 모델 네트워크에 대한 모든 노드를 반환

`model.childern()` : 같은 수준(level)의 하위 노드를 반환

![module/children](https://thebook.io/img/080289/053.jpg)

### **함수로 신경망 정의**


- 장점 : Sequential을 사용하는 것과 동일하지만, 함수로 선언할 경우 변수에 저장해 놓은 계층들을 재사용할 수 있음
- 단점 : 모델이 복잡해짐 (복잡한 모델의 경우, 함수를 이용하는 것보다는 nn.Module()을 상속받아 사용하는 것이 편리)
- ReLU, Softmax, Sigmoid와 같은 활성화 함수는 모델을 정의할 때 지정

In [ ]:
def MLP(in_features=1, hidden_features=20, out_features=1):
    hidden = nn.Linear(in_features=in_features, out_features=hidden_features, bias=True)
    activation = nn.ReLU()
    output = nn.Linear(in_features=hidden_features, out_features=out_features, bias=True)
    net = nn.Sequential(hidden, activation, output)
    return net

## **모델 파라미터 정의**

[사전에 정의할 파라미터 목록]

★**손실 함수(loss function)** : 학습하는 동안 출력과 실제 값(정답) 사이의 오차를 측정함. 즉, wx + b를 계산한 값과 실제 값인 y의 오차를 구해서 모델의 정확성을 측정
    
- 자주 사용하는 loss function

    • BCELoss: 이진 분류를 위해 사용

    • CrossEntropyLoss: 다중 클래스 분류를 위해 사용

    • MSELoss: 회귀 모델에서 사용

★**옵티마이저(optimizer)** : 데이터와 손실 함수를 바탕으로 모델의 업데이트 방법을 결정
- optimizer의 주요 특성

    • step() 메서드를 통해 전달받은 파라미터를 업데이트함

    • 모델의 파라미터별로 다른 기준(ex. 학습률) 적용 가능

    • `torch.optim.Optimizer(params, defaults)` : 모든 옵티마이저의 기본이 되는 클래스

    • `zero_grad()` : 옵티마이저에 사용된 파라미터들의 기울기(gradient)를 0으로 만들어줌

    • `torch.optim.lr_scheduler` : 에포크에 따라 학습률 조절 가능

- optimizer 종류

    • optim.Adadelta, optim.Adagrad, optim.Adam, optim.SparseAdam, optim.Adamax

    • optim.ASGD, optim.LBFGS

    • optim.RMSProp, optim.Rprop, optim.SGD

★**학습률 스케줄러(learning rate scheduler)** : 미리 지정한 횟수의 에포크를 지날 때마다 학습률을 감소(decay)시킴. 학습률 스케줄러를 이용하면 학습 초기에는 빠른 학습을 진행하다가 전역 최소점(global minimum) 근처에 다다르면 학습률을 줄여서 최적점을 찾아갈 수 있도록 함.
- 학습률 스케줄러의 종류

    • `optim.lr_scheduler.LambdaLR` : 람다(lambda) 함수를 이용하여 그 함수의 결과를 학습률로 설정

    • `optim.lr_scheduler.StepLR` : 특정 단계(step)마다 학습률을 감마(gamma) 비율만큼 감소시킴

    • `optim.lr_scheduler.MultiStepLR` : StepLR과 비슷하지만 특정 단계가 아닌 지정된 에포크에만 감마 비율로 감소시킴

    • `optim.lr_scheduler.ExponentialLR` : 에포크마다 이전 학습률에 감마만큼 곱함

    • `optim.lr_scheduler.CosineAnnealingLR` : 학습률을 코사인(cosine) 함수의 형태처럼 변화시킴 > 학습률이 커지기도, 작아지기도 함

    • `optim.lr_scheduler.ReduceLROnPlateau` : 학습이 잘되고 있는지 아닌지에 따라 동적으로 학습률을 변화시킬 수 있음

★**지표(metrics)**: 훈련과 테스트 단계를 모니터링



```
# 모델 파라미터를 정의하는 예시 코드
from torch.optim import optimizer
criterion = torch.nn.MSELoss()
optimizer = torch.optim.SGD(model.pareameters(), lr=0.01, momentum=0.9)
scheduler = torch.optim.lr_scheduler.LamdaLR(optimizer=optimizer, lr_lambda=lambda epoch: 0.95**epoch)

for epoch in range(1, 100+1):   # epoch 수만큼 데이터를 반복하여 처리
    for x, y in dataloader:
        optimizer.zero_grad()
loss_fn(model(x), y).backward()
optimizer.step()
scheduler.step()
```



## **모델 훈련**

모델을 학습시킨다 : $y = wx + b$ 함수에서 적절한 $w$와 $b$의 값을 찾는다!
- $w$와 $b$에 임의의 값을 적용하여 시작, 오차가 줄어들어 적역 최소점에 이를 때까지 파라미터$(w,b)$를 계속 수정

[모델 훈련 방법]

Step 1. `optimizer.zero_grad()` 메서드를 이용하여 기울기 초기화
- `loss.backward()` 메서드 : 새로운 기울기 값이 이전 기울기 값에 누적하여 계산됨
- 이는 RNN 모델을 구현할 때는 효과적이지만, 누적 계산이 필요하지 않은 모델에 대해서는 불필요함
- 따라서 기울기 값에 대해 누적 계산이 필요하지 않을 때는 입력값을 모델에 적용하기 전 `optimizer.zero_grad()` 메서드를 호출하여 미분 값을 초기화해 주어야 함

Step 2. `loss.backward()` 메서드를 이용하여 기울기를 자동 계산
- `loss.backward()` : 배치가 반복될 때마다 오차가 중첩적으로 쌓이게 되므로 미분값 초기화 필요!




```
# 모델 훈련 예시 코드

for epoch in range(100):
    yhat = model(x_train)
    loss = criterion(yhat, y_train)
    optimizer.zero_grad()  
    loss.backward()
    optimizer.step()
```

![training steps](https://thebook.io/img/080289/057.jpg)



## **모델 평가**

In [1]:
!pip install torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 961.5/961.5 kB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 27.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 20.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 33.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 87.3 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstall

In [2]:
# 함수를 이용한 모델 평가 코드
import torch
import torchmetrics

preds = torch.randn(10, 5).softmax(dim=-1)
target = torch.randint(5, (10,))

acc = torchmetrics.functional.accuracy(preds, target, task="multiclass", num_classes=5)

In [3]:
acc

tensor(0.3000)

In [6]:
# 모듈을 이용한 모델 평가 코드
metric = torchmetrics.Accuracy(task="multiclass", num_classes=5)   # 모델 평가(정확도) 초기화

n_batches = 10
for i in range(n_batches):
    preds = torch.randn(10, 5).softmax(dim=-1)
    target = torch.randint(5, (10,))

    acc = metric(preds, target)
    print(f"Accuracy on batch {i}: {acc}")   # 현재 배치에서 모델 평가

acc = metric.compute()
print(f'Accuracy on all data: {acc}')   # 모든 배치에서 모델 평가

Accuracy on batch 0: 0.30000001192092896
Accuracy on batch 1: 0.10000000149011612
Accuracy on batch 2: 0.10000000149011612
Accuracy on batch 3: 0.10000000149011612
Accuracy on batch 4: 0.10000000149011612
Accuracy on batch 5: 0.30000001192092896
Accuracy on batch 6: 0.0
Accuracy on batch 7: 0.20000000298023224
Accuracy on batch 8: 0.10000000149011612
Accuracy on batch 9: 0.4000000059604645
Accuracy on all data: 0.17000000178813934


## **훈련 과정 모니터링**

파이토치로 머신러닝/딥러닝 모델을 만들어 학습해보면 학습이 진행되는 과정에서 각 파라미터에 어떤 값들이 어떻게 변화하는지 모니터링하기 어려움
> **텐서보드**를 이용하면 학습에 사용되는 각종 파라미터 값이 어떻게 변화하는지 손쉽게 시각화하여 살펴볼 수 있음 + 성능을 추적, 평가하는 용도로도 사용 가능


```
!pip install tensorboard
```

```
# 텐서보드 사용 코드
import torch
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter("../chap02/tensorboard") ------ 모니터링에 필요한 값들이 저장될 위치

for epoch in range(num_epochs):
    model.train() ------ 학습 모드로 전환(dropout=True)
    batch_loss = 0.0

    for i, (x, y) in enumerate(dataloader):
        x, y = x.to(device).float(), y.to(device).float()
        outputs = model(x)
        loss = criterion(outputs, y)
        writer.add_scalar("Loss", loss, epoch) ------ 스칼라 값(오차)을 기록
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

writer.close() ------ SummaryWriter가 더 이상 필요하지 않으면 close( ) 메서드 호출
```
```
tensorboard --logdir=../chap02/tensorboard --port=6006
# 웹 브라우저에서 http://localhost:6006 입력 시 텐서보드 페이지가 열림
```

![tensorboard](https://thebook.io/img/080289/060.jpg)
