<a href="https://colab.research.google.com/github/wheemin-2/25-1-ESAA/blob/main/0411_HW_Recommendations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **추천 시스템**

**추천 시스템의 유형**

1. 콘텐츠 기반 필터링 방식

2. 협업 필터링 방식
    - 최근접 이웃 협업 필터링
    - 잠재 요인 협업 필터링


## **콘텐츠 기반 필터링 추천 시스템**

사용자가 특정한 아이템을 매우 선호하는 경우, 그 아이템과 비슷한 콘텐츠를 가진 다른 아이템을 추천하는 방식용자가 특정한 아이템을 매우 선호하는 경우, 그 아이템과 비슷한 콘텐츠를 가진 다른 아이템을 추천하는 방식

![content based filtering](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2F5cf5aa39-a095-455e-8eb8-27aaf49b026f%2Fimage.png)

## **협업 필터링 방식 추천 시스템**

사용자가 아이템에 매긴 평점 정보나 상품 구매 이력과 같은 사용자 행동 양식(User Behavior)만을 기반으로 추천을 수행하는 방식

**협업 필터링의 주요 목표**

: 사용자-아이템 평점 행렬과 같은 축적된 사용자 행동 데이터를 기바능로 사용자가 아직 평가하지 않은 아이템을 예측 평가(Predicted Rating)하는 것

![collaborative filtering](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2F8e54b423-3231-4317-88ec-38d8c012494b%2Fimage.png)

협업 필터링 기반의 추천 시스템은 최근접 이웃 방식과 잠재 요인 방식으로 나뉘고, 두 방식 모두 **사용자-아이템 평점 행렬 데이터**에만 의지하여 추천을 수행

**사용자-아이템 평점 행렬 데이터**

- 행(Row) : 개별 사용자
- 열(Column) : 개별 아이템
- 값 : 평점
- 데이터가 레코드 레벨 형태라면, `pd.pivot_table()`과 같은 함수를 사용하여 행렬 형태로 변경해야함
- 일반적으로 많은 아이템을 column으로 가지는 **다차원 행렬 + 희소 행렬** 특성을 가짐
    - 사용자가 아이템에 대한 평점을 매기는 경우가 많지 않기 때문

  ![user-item mtx](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2Fe46591a2-504d-4ba4-acbb-43414fca5a78%2Fimage.png)

### **최근접 이웃 협업 필터링**

메모리(Memory) 협업 필터링이라고도 하며, 일반적으로 사용자 기반과 아이템 기반으로 다시 나뉠 수 있음

- 사용자 기반 (User-User) : 당신과 비슷한 고객들이 다음 상품도 구매했습니다
- 아이템 기반 (Item-Item) : 이 상품을 선택한 다른 고객들은 다음 상품도 구매했습니다

**사용자 기반 최근접 이웃 방식**

: 특정 사용자와 유사한 다른 사용자를 Top-N으로 선정하여 이 Top-N 사용자가 좋아하는 아이템을 추천하는 방식

- 즉, 특정 사용자와 타 사용자 간의 유사도(Similarity)를 측정한 뒤 가장 유사도가 높은 Top-N 사용자를 추출해 그들이 선호하는 아이템을 추천하는 것

  ![user-user](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2Fbd4ad44a-cd30-49d5-890e-415506c33b49%2Fimage.png)

**아이템 기반 최근접 이웃 방식**

: 사용자들이 그 아이템을 좋아하는지/싫어하는지의 평가 척도가 유사한 아이템을 추천하는 기준이 되는 알고리즘 (아이템이 가지는 속성과는 상관 없음!)

 ![item-item](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2F2dcbb40a-7a14-47f6-8503-1c9bbb3dfc8d%2Fimage.png)

 - 사용자 기반 최근접 이웃 데이터 세트와 행과 열이 서로 반대
 - 아이템(영화) '다크나이트'는 '프로메테우스'와 상호 간 아이템 유사도가 상대적으로 높음 >> 아이템 기반 협업 필터링은 '다크나이트'를 좋아하는 사용자 D에게 '프로메테우스'를 추천함(스타워즈 vs. 프로메테우스일 때)


일반적으로 사용자 기반보다는 아이템 기반 협업 필터링이 정확도가 더 높음 >> Why??

- 비슷한 상품을 좋아한다고 해서 사람들의 취향이 비슷하다고 판단하기는 어려운 경우가 많음
- 매우 유명한 영화는 취향과 관계없이 대부분의 사람이 관람하는 경우가 많음
- 사용자들이 평점을 매긴 영화(또는 상품)의 개수가 많지 않은 경우가 일반적인데, 이를 기반으로 다른 사람과의 유사도를 비교하는 것 또한 어려움

*따라서 최근접 이웃 협업 필터링은 대부분 아이템 기반의 알고리즘을 적용*

### **잠재 요인 협업 필터링**

사용자-아이템 평점 매트릭스 속에 숨어 있는 잠재 요인을 추출해 추천 예측을 할 수 있게 하는 기법
- 대규모 다차원 행렬을 SVD와 같은 차원 감소 기법으로 분해하는 과정에서 잠재 요인을 추출 >> 행렬 분해 (Matrix Factorization) !!
- 잠재 요인을 기반으로 다차원 희소 행렬인 사용자-아이템 행렬 데이터를 저차원 밀집 행렬의 사용자-잠재 요인 행렬과 아이템-잠재 요인 행렬의 전치 행렬 (잠재 요인-아이템 행렬)로 분해가 가능
- '잠재 요인'이 어떤 것인지는 명확히 정의 불가능
    - 하지만 가령 영화 평점 기반의 사용자-아이템 평점 행렬 데이터라면 영화가 가지는 장르별 특성 선호도로 가정할 수 있음
    - 사용자-잠재 요인 행렬 : 사용자의 영화 장르에 대한 선호도
    - 아이템-잠재 요인 행렬 : 영화의 장르별 특성값으로 정의 가능

**잠재 요인 협력 필터링 알고리즘의 구조**

- 사용자-아이템 행렬 => 사용자-잠재요인 행렬 + (아이템-잠재요인 행렬).T 로 분해
    - 다차원 희소행렬에서 저차원 밀집 행렬로 분해 >> 행렬 분해 기법 (Matrix Factorization)

- 이렇게 분해된 두 행렬의 "내적"을 통해 새로운 예측 사용자-아이템 평점 행렬 데이터를 생성
- 사용자가 아직 평점을 부여하지 않은 아이템에 대한 예측 평점을 생성함

 ![latent factor](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2F4fac5e69-c54f-42b8-8303-1ae7ae5a8abd%2Fimage.png)


Notation

- R : 사용자 - 아이템 평점 행렬
    - R(u, i) : 사용자(User, u)의 아이템(Item, i)에 대한 평점
- P : 사용자 - 잠재요인 행렬 (사용자의 영화 장르별 선호도 행렬)
    - P(u, k), k : 장르별 선호도 (잠재요인 칼럼)
- Q : 영화의 장르별 요소 행렬
    - Q(i, k), k : 장르별 요소
    - 이후 P와의 내적 계산을 위해 transpose 진행, Q.T(k, i)
- 잠재요인 (가정)
    - factor 1 : 액션 선호도
    - factor 2 : 로맨스 선호도

**R=P*Q.T**
![svd](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2Fbd58557f-9545-4acd-8f9b-860cd9847af7%2Fimage.png)
*예측
![pred](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2F3e9c6825-d272-47cd-8809-a1ff3c543ebe%2Fimage.png)

*아이디어 부연 설명*

- 평점이란? : 사용자의 특정 영화 장르에 대한 선호도와 개별 영화의 그 장르적 특성값을 반영해 결정된다고 생각할 수 있음

- 예를 들어 사용자가 액션 영화를 매우 좋아하고, 특정 영화가 액션 영화의 특 성이 매우 크다면 사용자가 해당 영화에 높은 평점을 줄 것.
- 따라서 평점은 사용자의 장르별 선호도 벡터와 영화의 장르별 특성 벡터를 서로 곱해서 만들 수 있음.
- 즉, User 1 의 item 1의 평점인 R（1, 1）의 4점은 P 매트릭스의 User 1 벡터와 Q.T 매트릭스의 Item 1 벡터를 곱한 값으로 구할 수 있음
- 예측도 마찬가지 : R ( 1 , 2 ) 는 행렬 분해된 P 매트릭스의 User 1 벡터와 Q.T 매트릭스의 Item 2 벡터의 내적 결과값으로 예측 가능

#### **행렬 분해의 이해**

행렬 분해 : 다차원의 매트릭스를 저차원 매트릭스로 분해하는 기법

- SVD (Singular Vector Decomposition)
- NMF (Non-Negatvie Matrix Factorization)


![mtx factorization](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2F13e60118-374f-4edb-bd4d-aa2988fe142e%2Fimage.png)

R 행렬의 u행 사용자와 i열 아이템 위치에 있는 평점 데이터를 $r_{(u,i)}$ 라고 하면,

$ r_{(u,i)} = p_u * q^t_i $ 로 유추 가능

- $p_u$ : 행렬 P에서 u행 사용자의 vector
- $q^t_i$ : 행렬 Q의 i행 아이템 벡터의 transpose vector

사용자가 평가하지 않은 NaN(미정) 데이터에 대한 유추도 같은 방식으로 가능

 ![pred](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2F2d1699f5-90cc-4693-8778-cf7daeb293a9%2Fimage.png)

사용자-아이템 평점 행렬의 미정 값을 포함한 모든 평점 값은 행렬 분해를 통해 얻어진 P 행렬과 Q.T 행렬의 내적을 통하여 예측 평점으로 다시 계산 가능

**R ~ R_hat = P*Q.T**
![R_hat](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2Fe58cd971-975b-4df5-b823-bd6f2ec55445%2Fimage.png)

#### **확률적 경사 하강법을 이용한 행렬 분해**

*왜 SGD (Stochastic Gradient Descnet) 를 사용할까?*

행렬 분해는 주로 SVD 방식을 이용하지만, SVD는 **Null 값이 없는 행렬에만** 적용 가능

R 행렬에는 아직 평점이 입력되지 않은 Null 값이 많기 때문에 일반적인 SVD 방식으로는 P와 Q 행렬로 분해가 불가능함 >> 확률적 경사 하강법 (SGD) 이나 ALS 방식을 이용하여 SVD를 수행!

*SGD를 이용한 행렬 분해의 절차*

![SGD Step](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2F7fabb386-b63c-4701-9281-2bec7ddfd367%2Fimage.png)

*실제값과 예측값의 오류 최소화와 L2 규제를 고려한 비용 함수식*

![loss ft](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2F8598e529-7d9a-4e2e-b9b2-fc63752112f3%2Fimage.png)

*새롭게 업데이트되는 값 계산식*
![update](https://velog.velcdn.com/images%2Fgjtang%2Fpost%2Fe574176a-1209-46b7-9fe1-b0fa599c9e6e%2Fimage.png)

In [2]:
import numpy as np

# 원본 행렬 R 생성, 분해 행렬 P와 Q 초기화, 잠재 요인 차원 K는 3으로 설정
# R : 4*5 mtx
R = np.array([[4, np.nan, np.nan, 2, np.nan],
              [np.nan, 5, np.nan, 3, 1],
              [np.nan, np.nan, 3, 4, 4],
              [5, 2, 1, 2, np.nan]])
num_users, num_items = R.shape
K=3

# P와 Q 행렬의 크기를 지정하고 정규 분포를 가진 임의의 값으로 입력
np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))


In [3]:
from sklearn.metrics import mean_squared_error

def get_rmse(R, P, Q, non_zeros):
    error = 0
    # 두 개의 분해된 행렬 P와 Q.T의 내적으로 예측 R 행렬 생성
    full_pred_matrix = np.dot(P, Q.T)

    # 실제 R 행렬에서 NULL이 아닌 값의 위치 인덱스를 추출해 실제 R 행렬과 R_hat의 RMSE 추출
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)

    return rmse

In [4]:
# R > 0 인 행 위치, 열 위치, 값을 non_zeros 리스트에 저장
non_zeros = [ (i, j, R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j]>0 ]

steps = 1000
learning_rate = 0.01
r_lambda = 0.01

# SGD 기법으로 P와 Q matrix를 계속 업데이트
for step in range(steps):
    for i,j,r in non_zeros:
        # 실제 값과 예측 값의 차이인 오류 값 구하기
        eij = r - np.dot(P[i,:], Q[j,:].T)
        # l2 규제를 반영한 SGD 업데이트 공식 적용
        P[i, :] = P[i, :] + learning_rate * (eij * Q[j, :] - r_lambda*P[i, :])
        Q[j, :] = Q[j, :] + learning_rate * (eij * P[i, :] - r_lambda*Q[j, :])

        rmse = get_rmse(R, P, Q, non_zeros)
        if (step % 50) == 0 :
            print('### iteration step :', step, 'rmse :', rmse)

### iteration step : 0 rmse : 3.261355059488935
### iteration step : 0 rmse : 3.26040057174686
### iteration step : 0 rmse : 3.253984404542389
### iteration step : 0 rmse : 3.2521583839863624
### iteration step : 0 rmse : 3.252335303789125
### iteration step : 0 rmse : 3.251072196430487
### iteration step : 0 rmse : 3.2492449982564864
### iteration step : 0 rmse : 3.247416477570409
### iteration step : 0 rmse : 3.241926055455223
### iteration step : 0 rmse : 3.2400454107613084
### iteration step : 0 rmse : 3.240166740749792
### iteration step : 0 rmse : 3.2388050277987723
### iteration step : 50 rmse : 0.5003190892212748
### iteration step : 50 rmse : 0.5001616291326989
### iteration step : 50 rmse : 0.49899601202578087
### iteration step : 50 rmse : 0.4988483450145831
### iteration step : 50 rmse : 0.49895189256631756
### iteration step : 50 rmse : 0.49833236830090993
### iteration step : 50 rmse : 0.4984148489378701
### iteration step : 50 rmse : 0.49792599580240876
### iteration ste

In [5]:
# 분해된 P, Q 함수를 통해 예측 행렬 생성
pred_mtx = np.dot(P, Q.T)
print('예측 행렬:\n', np.round(pred_mtx, 3))

예측 행렬:
 [[3.991 0.897 1.306 2.002 1.663]
 [6.696 4.978 0.979 2.981 1.003]
 [6.677 0.391 2.987 3.977 3.986]
 [4.968 2.005 1.006 2.017 1.14 ]]


원본 행렬과 비교해 null이 아닌 값은 큰 차이 X, null인 값은 새로운 예측값으로 채워짐